# Homebrew formula template.
#
# `@VERSION@` and the `@SHA256_*@` placeholders are substituted by
# .github/workflows/homebrew.yaml from the published release assets, and the
# result is pushed to noirbizarre/homebrew-tap as Formula/over.rb.
class Over < Formula
  desc "A git-based file overlay manager (dotfiles as overlays)"
  homepage "https://noirbizarre.github.io/over/"
  version "@VERSION@"
  license "MIT"

  # Prebuilt binaries from the GitHub release rather than a source build:
  # installing takes no Rust toolchain, and libgit2/OpenSSL are already
  # vendored into each binary so there is nothing to link against.
  on_macos do
    on_arm do
      url "https://github.com/noirbizarre/over/releases/download/#{version}/over_#{version}_darwin-arm64.tar.gz"
      sha256 "@SHA256_DARWIN_ARM64@"
    end
    on_intel do
      url "https://github.com/noirbizarre/over/releases/download/#{version}/over_#{version}_darwin-amd64.tar.gz"
      sha256 "@SHA256_DARWIN_AMD64@"
    end
  end

  # musl rather than gnu: the binaries are statically linked, so they run on
  # any distribution Homebrew supports regardless of its glibc. There is no
  # aarch64-musl leg in the release matrix, so Linux arm64 is left
  # unsupported rather than served a glibc-pinned binary that would fail at
  # load time.
  on_linux do
    on_intel do
      url "https://github.com/noirbizarre/over/releases/download/#{version}/over_#{version}_linux-amd64-musl.tar.gz"
      sha256 "@SHA256_LINUX_AMD64_MUSL@"
    end
  end

  # Not a build dependency — a usage one. `git-over` is a git subcommand, and
  # `git over mount` is the workflow the documentation leads with.
  depends_on "git"

  def install
    # The archive holds `over` and `git-over` at its root, named exactly
    # that. `git-over`'s name is load-bearing: Git resolves `git over` only
    # through an executable called exactly `git-over` on PATH.
    bin.install "over"
    bin.install "git-over"

    # Generated by the binary rather than taken from the archive, because
    # that is the form Homebrew audits: it runs `over completion <shell>` for
    # each shell and files the output where that shell looks for it. `shell`
    # is a required positional argument with no flag form, so this relies on
    # Homebrew's default parameter format, which passes it plainly as a
    # trailing argument.
    generate_completions_from_executable(bin/"over", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/over --version")
    assert_match "overlay", shell_output("#{bin}/over --help")
    assert_match version.to_s, shell_output("#{bin}/git-over --version")
  end
end
