name: 👮 CI
on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: 🧪 Tests (${{ matrix.os.name }})
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - name: Linux
            runner: ubuntu-latest
          - name: Windows
            runner: windows-latest
          - name: macOS
            runner: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Run tests (with coverage)
        run: |
          cargo llvm-cov nextest --profile ci
          cargo llvm-cov report --lcov --output-path lcov.info

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !cancelled() }}
        with:
          directory: target/nextest/ci
          report_type: test_results
